let MCQS = [{
        //level A1-1
        question: "What's_____ name? She is Sussy.",
        choice1: "A) my",
        choice2: "B) your",
        choice3: "C) his",
        choice4: "D) her",
        answer: 3,
    },
    {
        question: "Do you _____ cooking? Of course.",
        choice1: "A) to Like",
        choice2: "B) liked",
        choice3: "C) like",
        choice4: "D) will like",
        answer: 2,
    },
    {
        question: "My friends _____ from Germany.",
        choice1: "A) is",
        choice2: "B) are",
        choice3: "c) am",
        choice4: "D) isn't",
        answer: 1,
    },
    {
        //level A1-2
        question: "_____ do you exercise? I exercise twice a week",
        choice1: "A) What time",
        choice2: "B) Where",
        choice3: "C) How often",
        choice4: "D) Who",
        answer: 2,
    },
    {
        question: "Why _____ crying? ",
        choice1: "A) is she",
        choice2: "B) she was",
        choice3: "C) did she",
        choice4: "D) she is",
        answer: 0,
    },
    {
        question: "A car is _____ than a cell phone",
        choice1: "A) the most expensive",
        choice2: "B) expensive",
        choice3: "C) more expensive",
        choice4: "as expensive as",
        answer: 2,
    },
    {
        //level A2-1
        question: "Anne _____ at home last night",
        choice1: "A) isn't",
        choice2: "B) didn't",
        choice3: "C) weren't",
        choice4: "D) wasn't",
        answer: 3,
    },
    {
        question: "  _____ you_____ Tv last night when I called you? What else ____ you do?",
        choice1: "A) Are/watching/ do",
        choice2: "B) Is/watching/do",
        choice3: "C) Were/watching /did",
        choice4: "D) Did/watch/did",
        answer: 2,
    },
    {
        question: "What did Estela use to do after school? She ______ every afternoon.",
        choice1: "A) plays basketball",
        choice2: "B) use to play basketball",
        choice3: "C) Used to",
        choice4: "D) used to play basketball",
        answer: 3,
    },
    {
        //level A2-2
        question: "Probably, I _____ go out for dinner",
        choice1: "A) going to",
        choice2: "B) maybe",
        choice3: "C) can",
        choice4: "D) will",
        answer: 3,
    },
    {
        question: "Is she_____ get married soon?",
        choice1: "A) going to",
        choice2: "B) can",
        choice3: "C) will",
        choice4: "D) might",
        answer: 0,
    },
    {
        question: "What time are you _____ home tomorrow morning? At about 8 oclock",
        choice1: "A) leave",
        choice2: "B) left",
        choice3: "C) leaving",
        choice4: "D) to leave",
        answer: 2,
    },
    {
        //level b1-1
        question: "Where _____ you been? I _____ seen you since school",
        choice1: "A) have/have",
        choice2: "B) have/haven't",
        choice3: "C) has/hasn't",
        choice4: "D) haven't/have",
        answer: 1,
    },
    {
        question: "I _______ an interesting novel recently ",
        choice1: "A) am reading",
        choice2: "B) were reading",
        choice3: "C) have been reading",
        choice4: "D) read",
        answer: 2,
    },
    {
        question: "How long have you been learning English? I have been studying it _______ 3 years ago.",
        choice1: "A) for",
        choice2: "B) from",
        choice3: "C) since",
        choice4: "D) for about",
        answer: 2,
    },

    {
        //level b1-2
        question: "I would rather ________at home than ________to that event. ",
        choice1: "A) stay/attend",
        choice2: "B)stay/attended",
        choice3: "C) stayed/attend",
        choice4: "D) staying/attending",
        answer: 0,
    },
    {
        question: "Do you ________ in the city or the suburbs? ",
        choice1: "A) living",
        choice2: "B) would you prefer living",
        choice3: "C) prefer living",
        choice4: "D) prefer",
        answer: 2,
    },
    {
        question: "Jose: I am having a surprise birthday party for Alex. Do you want to go? Luz: It would be great, __________. Maybe next time",
        choice1: "A) unfortunately I have to work.",
        choice2: "B) How can I help?",
        choice3: "C) What time is it going to be?",
        choice4: "D) I do not want.",
        answer: 0,
    },
    {
        //level b1-3
        question: "Every time the manager hires new staff, he _______ take experience into consideration. ",
        choice1: "A) can",
        choice2: "B) might",
        choice3: "C) should",
        choice4: "D) could",
        answer: 2,
    },
    {
        question: "You ________ follow the rules and regulations of your school and city to avoid problems. ",
        choice1: "A) may",
        choice2: "B) must",
        choice3: "C) musn't",
        choice4: "D) shouldn't",
        answer: 1,
    },
    {
        question: "I ________ design a test for my students this week because the coordinator asked for it. ",
        choice1: "A) can",
        choice2: "B) should",
        choice3: "C) have to",
        choice4: "D) might",
        answer: 2,
    },

    {
        //level b1-4
        question: "Don't forget the umbrella because if it _______, you will get wet",
        choice1: "A) rain",
        choice2: "B) rains",
        choice3: "C) rained",
        choice4: "D) will rain",
        answer: 1,
    },

    {
        question: "You get water if you ..... hydrogen and oxygen",
        choice1: "A) mix",
        choice2: "B) mixes",
        choice3: "C) mixed",
        choice4: "D) will mix",
        answer: 0,
    },

    {
        question: "If my students spoke English fluently, I _____ English during the whole class.",
        choice1: "A) would have spoken",
        choice2: "B) would speak",
        choice3: "C) will speak",
        choice4: "D) spoke",
        answer: 1,
    },

    {
        //level b2-1
        question: "____do you agree with the followig statement?",
        choice1: "A) Up to",
        choice2: "B) At what",
        choice3: "C) To what extent",
        choice4: "D) On what",
        answer: 2,
    },
    {
        question: "____I am concerned ",
        choice1: "A) As here as",
        choice2: "B) As far as",
        choice3: "C) As where as",
        choice4: "D) As what as",
        answer: 1,
    },
    {
        question: "'I will leave for  New York tomorrow', She said:_____ ",
        choice1: "A) She will leave",
        choice2: "B) She leaves",
        choice3: "C) She would leave",
        choice4: "D) She left",
        answer: 2,
    },
    {
        //level b2-2
        question: "It  has _____ that 80% of the population is under alert",
        choice1: "A) been said",
        choice2: "B) say",
        choice3: "C) said",
        choice4: "D) must be said",
        answer: 0,
    },
    {
        question: "What _____by the journalists?",
        choice1: "A) was observing",
        choice2: "B) was observed",
        choice3: "C) observed",
        choice4: "D) were observed",
        answer: 1,
    },
    {
        question: "It had been _____ by the founders",
        choice1: "A) carried out",
        choice2: "B) carry out",
        choice3: "C) carries out",
        choice4: "D) carrying out",
        answer: 0,
    },
    {
        //level b2-3
        question: "I'm getting _______ the noise now. I found it stressful when I first moved in. ",
        choice1: "A) use to",
        choice2: "B) uses",
        choice3: "C) used to",
        choice4: "D) to use",
        answer: 2,
    },
    {
        question: "It took my mother years to_________ in London after moving from Pakistan.",
        choice1: "A) use to live",
        choice2: "B) getting used to live",
        choice3: "C) used to live",
        choice4: "D) get used to living",
        answer: 3,
    },
    {
        question: "I _____ trying to stop drinking soda even before the doctor told me.",
        choice1: "A) would have been",
        choice2: "B) had been",
        choice3: "C) have been",
        choice4: "D) would be",
        answer: 1,
    },
    {
        //level b2-4
        question: "If you had studied hard, you _____ the exam",
        choice1: "A) will pass",
        choice2: "B) will have to pass",
        choice3: "C) would have passed",
        choice4: "D) would pass",
        answer: 2,
    },

    {
        question: "We would have gone out if the rain ____",
        choice1: "A) had stopped",
        choice2: "B) would stop",
        choice3: "C) have stopped",
        choice4: "D) has stopped",
        answer: 0,
    },
    {
        question: "Missing word indicates example: _____, several of the following species which have beeen recently found are endangered",
        choice1: "A) Finally",
        choice2: "B) Consequently",
        choice3: "C) For instance",
        choice4: "D) Therefore",
        answer: 2,
    },
    {
        //level C-1
        question: "Don't put your glass of water on the ...... of the table - someone will knock it off.",
        choice1: "A) border",
        choice2: "B) boundary",
        choice3: "C) extremity",
        choice4: "D) edge",
        answer: 3,
    },
    {
        question: "When I realised I had dropped my keys, I decided to ..... my steps",
        choice1: "A) go back",
        choice2: "B) watch",
        choice3: "C) return",
        choice4: "D) retrace",
        answer: 3,
    },
    {
        question: "It is a fact rather than _____ thinking",
        choice1: "A) wish",
        choice2: "B) wishful",
        choice3: "C) wishes",
        choice4: "D) wishing",
        answer: 1,
    },
    {
        question: "The position was set focused on____they had better academic qualifications",
        choice1: "A) Weather",
        choice2: "B) Weather or not",
        choice3: "C) Whether",
        choice4: "D) Wether or not",
        answer: 3,
    },
    {
        question: "The group has achieved a victory, against _____ ",
        choice1: "A) all of",
        choice2: "B) all above",
        choice3: "C) all odds",
        choice4: "D) all of the above",
        answer: 2,
    },
    {
        question: "I can't ____ the thought of having to start all over",
        choice1: "A) bears",
        choice2: "B) beared",
        choice3: "C) bearing",
        choice4: "D) bear",
        answer: 3,
    },

];